# Generated by Django 5.2.2 on 2025-06-17 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='scheduled_date',
        ),
    ]
