# Generated by Django 5.2.2 on 2025-07-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='redirect_urls',
            field=models.URLField(blank=True, null=True),
        ),
    ]
