# Generated by Django 5.2.2 on 2025-07-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_notification_redirect_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='model_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='model_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
